unets:
  unet1: # BASE
    image_size: 128
    in_channels: 1
    out_channels: 1
    model_channels: 128
    emb_channels: 512
    channel_multipliers: [1, 1, 2, 3, 4]
    num_resnet_blocks: 2
    resnet_dropout: 0.1
    attn_resolution: [16, ]
    use_conv_resample: True
    num_groups: 32

encoders: 
  encoder1:
    image_size: 128
    in_channels: 1
    out_channels: 1
    model_channels: 128
    emb_channels: 512
    channel_multipliers: [1, 1, 2, 3, 4, 4]
    num_resnet_blocks: 2
    resnet_dropout: 0.1
    attn_resolution: [16, ]
    use_conv_resample: True
    num_groups: 32

cascaded: 
  image_sizes: [128]
  channels: 1
  temporal_downsample_factor: [1]
  text_embed_dim: 512

trainer:
  fp16: False
  grad_accum_steps: 1.0
  epoch: 300

  gradient_clipping:
    clip_grads: 1.0
  
  timestep_sampler: 
    num_sample_steps: 1000
    sample: uniform
  
  loss:
    name: SimpleLoss
  
  optimizer:
    name: Adam
    params:
        lr: 0.0001
        weight_decay: 0
  
  beta:
    schedule: linear
    linear:
        start: 0.0001
        end: 0.02
    cosine:
        s: 0.008
        max_beta: 0.999

dataset:
  data_path: "/vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentations/subjects/"  # datapath 
  sbj_file: "/vol/aimspace/users/bubeckn/MRIDiffusion/twelve-sliced-subjects.txt"         # file which defines the subjects to train on
  deactivate_cache: False
  time_res: 8 # IMPORTANT CHANGE IN 1SCM: 8fps instead of 32fps
  slice_res: gt
  res: 128 # resolution
  fps: 32 # frames per second
  duration: 1 #seconds
  grayscale: False
  use_la: False
  use_seg: False
  cond_slices: [5]
  train_pct: 0.8
  time_idx: 0
  
  train: 
    transforms:
      - name: RandomHorizontalFlip
        params:
            p: 0.0
      - name: RandomVerticalFlip
        params:
            p: 0.0

  test: 
    transforms:
      - name: RandomHorizontalFlip
        params:
            p: 0.0
      - name: RandomVerticalFlip
        params:
            p: 0.0

dataloader: # This is adapted when launching the training script
  batch_size: 8
  num_workers: 8

wandb:
  project: "MRIdiffae"
  entity: "niklas-bubeck"

checkpoint:
  path: "./outputs/diffusion"
  batch_size: 4
  cond_scale: 5.
  log_every_x_it: 50
  save_every_x_it: 50

seed: 42