unets:
  unet1: # BASE
    image_size: 128
    in_channels: 1
    out_channels: 1
    model_channels: 32
    emb_channels: 512
    channel_multipliers: [1, 2, 4]
    num_resnet_blocks: 2
    resnet_dropout: 0.1
    attn_resolution: [16, ]
    use_conv_resample: True
    num_groups: 32

encoders: 
  encoder1:
    image_size: 128
    in_channels: 1
    out_channels: 1
    model_channels: 32
    emb_channels: 512
    channel_multipliers: [1, 2, 4]
    num_resnet_blocks: 2
    resnet_dropout: 0.1
    attn_resolution: [16, ]
    use_conv_resample: True
    num_groups: 32


cascaded: 
  image_sizes: [64, 128]
  channels: 1
  temporal_downsample_factor: [1, 1]
  text_embed_dim: 512

trainer:
  fp16: False                                                  # if to use automatic mixec precision
  grad_accum_steps: 1.0                                        # number of steps to accumulate the gradients for 
  epoch: 300                                                   # number of epochs 

  gradient_clipping:                                           # where to gradient clip 
    clip_grads: 1.0
  
  timestep_sampler:                                            
    num_sample_steps: 1000                                     # number of timesampling steps for the DM encoding/decoding
    sample: uniform                                            # the way the noise gets sampled 
  
  loss:
    seg: dice                                           # dice, mse
    recon: mse 
    weight: 0.1                                         # ssim, mse
    tgrad: False
    tweight: 1

  optimizer:
    name: Adam
    params:
        lr: 0.0001
        weight_decay: 0
  
  beta:
    schedule: linear
    linear:
        start: 0.0001
        end: 0.02
    cosine:
        s: 0.008
        max_beta: 0.999

dataset:
  data_path: "/vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentations/projects/MedMAE"  # datapath   /vol/aimspace/projects/ukbb/data/cardiac/cardiac_segmentations/projects/MedMAE
  sbj_file: null #"/vol/aimspace/users/bubeckn/MRIDiffusion/twelve-sliced-subjects.txt"         # file which defines the subjects to train on
  deactivate_cache: False
  time_res: 5 # IMPORTANT CHANGE IN 1SCM: 8fps instead of 32fps
  slice_res: 8
  res: 128 # resolution
  fps: 32 # frames per second
  duration: 1 #seconds
  grayscale: False
  use_la: False
  use_seg: False
  cond_slices: [5]
  train_pct: 0.8
  time_idx: null
  
  train: 
    transforms:
      - name: RandomHorizontalFlip
        params:
            p: 0.0
      - name: RandomVerticalFlip
        params:
            p: 0.0

  test: 
    transforms:
      - name: RandomHorizontalFlip
        params:
            p: 0.0
      - name: RandomVerticalFlip
        params:
            p: 0.0

dataloader: # This is adapted when launching the training script
  batch_size: 8
  num_workers: 8

wandb:
  project: "DMCVR"
  entity: "videomri"

checkpoint:
  path: "./outputs/diffusion"
  batch_size: 4
  cond_scale: 5.
  log_every_x_it: 10
  save_every_x_it: 10

seed: 42
three_d: True
num_classes: 4